package tfc.renirol.frontend.rendering.enums;

import org.lwjgl.vulkan.KHRSwapchain;
import org.lwjgl.vulkan.VK13;

public enum ImageLayout {
    GENERAL(VK13.VK_IMAGE_LAYOUT_GENERAL),
    INITIALIZED(VK13.VK_IMAGE_LAYOUT_PREINITIALIZED),
    COLOR_ATTACHMENT_OPTIMAL(VK13.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),
    UNDEFINED(VK13.VK_IMAGE_LAYOUT_UNDEFINED),
    PRESENT(KHRSwapchain.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR),
    DEPTH_ATTACHMENT_OPTIMAL(VK13.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL),
    STENCIL_ATTACHMENT_OPTIMAL(VK13.VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL),
    DEPTH_STENCIL_ATTACHMENT_OPTIMAL(VK13.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL),
    SHADER_READONLY(VK13.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL),
    TRANSFER_DST_OPTIMAL(VK13.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL),
    TRANSFER_SRC_OPTIMAL(VK13.VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL),
    ;

    public final int value;

    ImageLayout(int value) {
        this.value = value;
    }
}
