/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tfc_renirol_util_accel_memory_cpp_BestFitManager */

#ifndef _Included_tfc_renirol_util_accel_memory_cpp_BestFitManager
#define _Included_tfc_renirol_util_accel_memory_cpp_BestFitManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tfc_renirol_util_accel_memory_cpp_BestFitManager
 * Method:    generate
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_tfc_renirol_util_accel_memory_cpp_BestFitManager_generate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     tfc_renirol_util_accel_memory_cpp_BestFitManager
 * Method:    allocate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_tfc_renirol_util_accel_memory_cpp_BestFitManager_allocate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     tfc_renirol_util_accel_memory_cpp_BestFitManager
 * Method:    release
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_tfc_renirol_util_accel_memory_cpp_BestFitManager_release
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     tfc_renirol_util_accel_memory_cpp_BestFitManager
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tfc_renirol_util_accel_memory_cpp_BestFitManager_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
