package tfc.renirol.frontend.rendering.enums.masks;

import org.lwjgl.vulkan.VK13;

public enum DynamicStateMasks {
    SCISSOR(VK13.VK_DYNAMIC_STATE_SCISSOR),
    VIEWPORT(VK13.VK_DYNAMIC_STATE_VIEWPORT),
    BLEND(VK13.VK_DYNAMIC_STATE_BLEND_CONSTANTS),
    FRONT_FACE(VK13.VK_DYNAMIC_STATE_FRONT_FACE),
    DEPTH_TEST(VK13.VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE),
    CULL_MODE(VK13.VK_DYNAMIC_STATE_CULL_MODE),
    MULTI_SCISSOR(VK13.VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT),
    PRIMITIVE_TOPOLOGY(VK13.VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY),
    PRIMITIVE_RESTART(VK13.VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE),
    LINE_WIDTH(VK13.VK_DYNAMIC_STATE_LINE_WIDTH),
    ;

    public final int bits;

    DynamicStateMasks(int bits) {
        this.bits = bits;
    }
}
