package tfc.renirol.frontend.enums.flags;

import org.lwjgl.vulkan.VK13;

public enum SwapchainUsage {
    COLOR(VK13.VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK13.VK_IMAGE_ASPECT_COLOR_BIT),
    SAMPLED(VK13.VK_IMAGE_USAGE_SAMPLED_BIT, VK13.VK_IMAGE_ASPECT_NONE),
    DEPTH(VK13.VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK13.VK_IMAGE_ASPECT_DEPTH_BIT),
    STENCIL(VK13.VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK13.VK_IMAGE_ASPECT_STENCIL_BIT),
    DEPTH_STENCIL(VK13.VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK13.VK_IMAGE_ASPECT_DEPTH_BIT | VK13.VK_IMAGE_ASPECT_STENCIL_BIT),
    GENERIC(VK13.VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK13.VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK13.VK_IMAGE_USAGE_SAMPLED_BIT, VK13.VK_IMAGE_ASPECT_COLOR_BIT),
    ;

    public final int id;
    public final int aspect;

    SwapchainUsage(int id, int aspect) {
        this.id = id;
        this.aspect = aspect;
    }
}
