/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tfc_renirol_util_windows_ReniUser32 */

#ifndef _Included_tfc_renirol_util_windows_ReniUser32
#define _Included_tfc_renirol_util_windows_ReniUser32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tfc_renirol_util_windows_ReniUser32
 * Method:    SetCapture
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_tfc_renirol_util_windows_ReniUser32_SetCapture
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tfc_renirol_util_windows_ReniUser32
 * Method:    GetCapture
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tfc_renirol_util_windows_ReniUser32_GetCapture
  (JNIEnv *, jclass);

/*
 * Class:     tfc_renirol_util_windows_ReniUser32
 * Method:    ReleaseCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tfc_renirol_util_windows_ReniUser32_ReleaseCapture
  (JNIEnv *, jclass);

/*
 * Class:     tfc_renirol_util_windows_ReniUser32
 * Method:    GetDoubleClickTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tfc_renirol_util_windows_ReniUser32_GetDoubleClickTime
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_tfc_renirol_util_windows_ReniUser32_GetClientRect
(JNIEnv *, jclass, jlong hwnd, jlong rect);

#ifdef __cplusplus
}
#endif
#endif
