/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tfc_renirol_util_windows_PerformanceCounters */

#ifndef _Included_tfc_renirol_util_windows_PerformanceCounters
#define _Included_tfc_renirol_util_windows_PerformanceCounters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tfc_renirol_util_windows_PerformanceCounters
 * Method:    QueryPerformanceFrequency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tfc_renirol_util_windows_PerformanceCounters_QueryPerformanceFrequency
  (JNIEnv *, jclass);

/*
 * Class:     tfc_renirol_util_windows_PerformanceCounters
 * Method:    QueryPerformanceCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tfc_renirol_util_windows_PerformanceCounters_QueryPerformanceCounter
  (JNIEnv *, jclass);
JNIEXPORT jlong JNICALL Java_tfc_renirol_util_windows_PerformanceCounters_GetTickCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
