package tfc.renirol.frontend.rendering.enums.modes;

import org.lwjgl.vulkan.VK13;

public enum PrimitiveType {
    TRIANGLE(VK13.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST),
    TRIANGLE_FAN(VK13.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN),
    TRIANGLE_STRIP(VK13.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP),
    POINT(VK13.VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
    LINE(VK13.VK_PRIMITIVE_TOPOLOGY_LINE_LIST),
    LINE_STRIP(VK13.VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
    PATCH(VK13.VK_PRIMITIVE_TOPOLOGY_PATCH_LIST),
    ;

    public final int id;

    PrimitiveType(int id) {
        this.id = id;
    }
}
