package tfc.renirol.frontend.enums;

import org.lwjgl.vulkan.VK13;

public enum DescriptorType {
    STORAGE_BUFFER(VK13.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
    DYNAMIC_STORAGE_BUFFER(VK13.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC),
    STORAGE_IMAGE(VK13.VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
    UNIFORM_BUFFER(VK13.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER),
    DYNAMIC_UNIFORM_BUFFER(VK13.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC),
    INLINE_UNIFORM(VK13.VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK),
    SAMPLED_IMAGE(VK13.VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE),
    SAMPLER(VK13.VK_DESCRIPTOR_TYPE_SAMPLER),
    COMBINED_SAMPLED_IMAGE(VK13.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER),
    ;

    public final int id;

    DescriptorType(int id) {
        this.id = id;
    }
}
